### ISSUE TITLE
Use of 4gl-excel in DataDigger

### ISSUE THREAD

**Issue by patrickTingen** [rodolfoag/4gl-excel#2]
Hi Rodolfoag, 

Not really an issue, but more a question: I came accross your code to generate an excel file in Progress 4GL. Since I use this functionality in my project DataDigger as well and since your solution is much more elegant than mine, I would like to use it in DataDigger if you allow me. Obviously, credits for you will be preserved in the code :)

For your info, DataDigger is an open source tool to check the contents of a Progress DB, check https://github.com/patrickTingen/DataDigger or for more info on DD

**Comment by rodolfoag** [comment]
Hi Patrick,
Yes of course, feel free to use it in any project you have. I'll update the license when I have some time.
Cheers

**Comment by rodolfoag** [comment]
License updated.

**Comment by patrickTingen** [comment]
Cool, thanks very much!

Kind regards,
Patrick Tingen


Op do 28 mrt. 2019 om 14:45 schreef Rodolfo Goncalves <
notifications@github.com>:
